---
galaxy_info:
  author: yamal
  description: Installs and configures Nginx.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
